# RSO-80: Assess the Scheduler CSC configuration time after enabling

**Descripcion**

I was interested in evaluating the time from when the scheduler CSC is enabled, to when the scheduler CSC is configured.

 

The context for this is to evaluate the overall latency of the Rubin ToO system. We have advanced information from the LVK side, and 2/5 of the Rubin steps for observing. 

 

My thought would be to evaluate this over the entire commissioning period, OR over a period of time since we have deployed any improvements to minimize the configure time.

In [2]:
import matplotlib.pyplot as plt
import pandas as pd

from lsst.summit.utils.efdUtils import (
    getEfdData,
    getDayObsEndTime,
    getDayObsForTime,
    getDayObsStartTime,
    makeEfdClient,
)
from astropy.time import Time

In [3]:
# Initialize an EFD client
efd_client = makeEfdClient()

In [100]:
# day_obs = 20250601
start_time = Time("2026-01-10T00:00:00Z", scale="utc")
end_time = Time("2026-01-15T23:30:00Z", scale="utc")

df = getEfdData(
        client=efd_client,
        topic="lsst.sal.Scheduler.command_addBlock",
        columns=["*"],
        begin=start_time,
        end=end_time,
)

## ************************

In [121]:
# Disable
df_disable = getEfdData(
             client=efd_client,
             topic="lsst.sal.Scheduler.command_disable",
             columns=["*"],
             begin=start_time,
             end=end_time,
)

In [122]:
df_disable['timestamp'] = df_disable.index

In [123]:
df_disable

,private_efdStamp,private_identity,private_kafkaStamp,private_origin,private_rcvStamp,private_revCode,private_seqNum,private_sndStamp,salIndex,timestamp
2026-01-10 01:21:51.755275+00:00,1.768008e+09,Script:111453,1.768008e+09,3400085,0,9c0ea436,326174075,1.768008e+09,1,2026-01-10 01:21:51.755275+00:00
2026-01-10 23:51:10.728102+00:00,1.768089e+09,Script:213822,1.768089e+09,3988392,0,9c0ea436,326174075,1.768089e+09,2,2026-01-10 23:51:10.728102+00:00
2026-01-11 00:32:34.236172+00:00,1.768092e+09,Script:112073,1.768092e+09,3946145,0,9c0ea436,326174075,1.768092e+09,1,2026-01-11 00:32:34.236172+00:00
2026-01-11 01:36:26.601585+00:00,1.768095e+09,Script:213884,1.768095e+09,4023197,0,9c0ea436,326174075,1.768095e+09,2,2026-01-11 01:36:26.601585+00:00
2026-01-11 14:09:01.513233+00:00,1.768141e+09,Script:214385,1.768141e+09,141507,0,9c0ea436,326174075,1.768141e+09,2,2026-01-11 14:09:01.513233+00:00
2026-01-12 00:07:05.932101+00:00,1.768176e+09,Script:214416,1.768176e+09,150391,0,9c0ea436,326174075,1.768176e+09,2,2026-01-12 00:07:05.932101+00:00
2026-01-12 07:03:19.758704+00:00,1.768201e+09,Script:112758,1.768201e+09,376781,0,9c0ea436,326174075,1.768201e+09,1,2026-01-12 07:03:19.758704+00:00
2026-01-12 23:51:16.872159+00:00,1.768262e+09,Script:215018,1.768262e+09,504670,0,9c0ea436,326174075,1.768262e+09,2,2026-01-12 23:51:16.872159+00:00
2026-01-13 04:39:10.763242+00:00,1.768279e+09,Script:112987,1.768279e+09,535953,0,9c0ea436,326174075,1.768279e+09,1,2026-01-13 04:39:10.763242+00:00
2026-01-13 23:51:24.910814+00:00,1.768348e+09,Script:215427,1.768348e+09,744080,0,9c0ea436,326174075,1.768348e+09,2,2026-01-13 23:51:24.910814+00:00
2026-01-14 20:59:50.877005+00:00,1.768424e+09,Script:113374,1.768424e+09,825369,0,9c0ea436,326174075,1.768424e+09,1,2026-01-14 20:59:50.877005+00:00
2026-01-14 23:51:16.046675+00:00,1.768435e+09,Script:216026,1.768435e+09,1091779,0,9c0ea436,326174075,1.768435e+09,2,2026-01-14 23:51:16.046675+00:00
2026-01-15 20:42:09.879622+00:00,1.768510e+09,Script:113462,1.768510e+09,872404,0,9c0ea436,326174075,1.768510e+09,1,2026-01-15 20:42:09.879622+00:00

In [124]:
# Enable
df_enable = getEfdData(
            client=efd_client,
            topic="lsst.sal.Scheduler.command_enable",
            columns=["*"],
            begin=start_time,
            end=end_time,
)

In [125]:
df_enable['timestamp'] = df_enable.index
df_enable

,private_efdStamp,private_identity,private_kafkaStamp,private_origin,private_rcvStamp,private_revCode,private_seqNum,private_sndStamp,salIndex,timestamp
2026-01-10 01:27:23.198661+00:00,1.768008e+09,Script:111453,1.768008e+09,3400085,0,4123e633,476961495,1.768008e+09,1,2026-01-10 01:27:23.198661+00:00
2026-01-10 23:51:45.790239+00:00,1.768089e+09,Script:213822,1.768089e+09,3988392,0,4123e633,476961495,1.768089e+09,2,2026-01-10 23:51:45.790239+00:00
2026-01-11 00:37:43.405530+00:00,1.768092e+09,Script:112073,1.768092e+09,3946145,0,4123e633,476961495,1.768092e+09,1,2026-01-11 00:37:43.405530+00:00
2026-01-11 01:37:04.950707+00:00,1.768095e+09,Script:213884,1.768095e+09,4023197,0,4123e633,476961495,1.768095e+09,2,2026-01-11 01:37:04.950707+00:00
2026-01-11 14:09:38.495453+00:00,1.768141e+09,Script:214385,1.768141e+09,141507,0,4123e633,476961495,1.768141e+09,2,2026-01-11 14:09:38.495453+00:00
2026-01-12 00:07:57.981250+00:00,1.768176e+09,Script:214416,1.768177e+09,150391,0,4123e633,476961495,1.768177e+09,2,2026-01-12 00:07:57.981250+00:00
2026-01-12 07:09:15.012064+00:00,1.768202e+09,Script:112758,1.768202e+09,376781,0,4123e633,476961495,1.768202e+09,1,2026-01-12 07:09:15.012064+00:00
2026-01-12 23:51:54.150495+00:00,1.768262e+09,Script:215018,1.768262e+09,504670,0,4123e633,476961495,1.768262e+09,2,2026-01-12 23:51:54.150495+00:00
2026-01-13 04:44:51.623314+00:00,1.768279e+09,Script:112987,1.768280e+09,535953,0,4123e633,476961495,1.768280e+09,1,2026-01-13 04:44:51.623314+00:00
2026-01-13 23:52:00.632737+00:00,1.768348e+09,Script:215427,1.768348e+09,744080,0,4123e633,476961495,1.768348e+09,2,2026-01-13 23:52:00.632737+00:00
2026-01-14 21:05:05.902047+00:00,1.768425e+09,Script:113374,1.768425e+09,825369,0,4123e633,476961495,1.768425e+09,1,2026-01-14 21:05:05.902047+00:00
2026-01-14 23:51:54.183704+00:00,1.768435e+09,Script:216026,1.768435e+09,1091779,0,4123e633,476961495,1.768435e+09,2,2026-01-14 23:51:54.183704+00:00
2026-01-15 20:47:30.517820+00:00,1.768510e+09,Script:113462,1.768510e+09,872404,0,4123e633,476961495,1.768510e+09,1,2026-01-15 20:47:30.517820+00:00

In [126]:
# Exit Control
df_exitControl = getEfdData(
                 client=efd_client,
                 topic="lsst.sal.Scheduler.command_exitControl",
                 columns=["*"],
                 begin=start_time,
                 end=end_time,
)

In [127]:
df_exitControl['timestamp'] = df_exitControl.index
df_exitControl

Empty DataFrame
Columns: [timestamp]
Index: []

In [129]:
# setLogLevel
df_setLogLevel = getEfdData(
                 client=efd_client,
                 topic="lsst.sal.Scheduler.command_setLogLevel",
                 columns=["*"],
                 begin=start_time,
                 end=end_time,
)

In [130]:
df_setLogLevel['timestamp'] = df_setLogLevel.index
df_setLogLevel

Empty DataFrame
Columns: [timestamp]
Index: []

In [132]:
# standby
df_standby = getEfdData(
             client=efd_client,
             topic="lsst.sal.Scheduler.command_standby",
             columns=["*"],
             begin=start_time,
             end=end_time,
)

In [133]:
df_standby['timestamp'] = df_standby.index
df_standby

,private_efdStamp,private_identity,private_kafkaStamp,private_origin,private_rcvStamp,private_revCode,private_seqNum,private_sndStamp,salIndex,timestamp
2026-01-10 01:21:57.334168+00:00,1.768008e+09,Script:111453,1.768008e+09,3400085,0,cd1b64f4,1616103400,1.768008e+09,1,2026-01-10 01:21:57.334168+00:00
2026-01-10 23:51:16.307530+00:00,1.768089e+09,Script:213822,1.768089e+09,3988392,0,cd1b64f4,1616103400,1.768089e+09,2,2026-01-10 23:51:16.307530+00:00
2026-01-11 00:32:39.820630+00:00,1.768092e+09,Script:112073,1.768092e+09,3946145,0,cd1b64f4,1616103400,1.768092e+09,1,2026-01-11 00:32:39.820630+00:00
2026-01-11 01:36:32.176299+00:00,1.768095e+09,Script:213884,1.768095e+09,4023197,0,cd1b64f4,1616103400,1.768095e+09,2,2026-01-11 01:36:32.176299+00:00
2026-01-11 14:09:07.086490+00:00,1.768141e+09,Script:214385,1.768141e+09,141507,0,cd1b64f4,1616103400,1.768141e+09,2,2026-01-11 14:09:07.086490+00:00
2026-01-12 00:07:11.494748+00:00,1.768176e+09,Script:214416,1.768176e+09,150391,0,cd1b64f4,1616103400,1.768176e+09,2,2026-01-12 00:07:11.494748+00:00
2026-01-12 07:03:25.306961+00:00,1.768201e+09,Script:112758,1.768201e+09,376781,0,cd1b64f4,1616103400,1.768201e+09,1,2026-01-12 07:03:25.306961+00:00
2026-01-12 23:51:22.475054+00:00,1.768262e+09,Script:215018,1.768262e+09,504670,0,cd1b64f4,1616103400,1.768262e+09,2,2026-01-12 23:51:22.475054+00:00
2026-01-13 04:39:16.316808+00:00,1.768279e+09,Script:112987,1.768279e+09,535953,0,cd1b64f4,1616103400,1.768279e+09,1,2026-01-13 04:39:16.316808+00:00
2026-01-13 23:51:30.485094+00:00,1.768348e+09,Script:215427,1.768348e+09,744080,0,cd1b64f4,1616103400,1.768348e+09,2,2026-01-13 23:51:30.485094+00:00
2026-01-14 20:59:56.440064+00:00,1.768424e+09,Script:113374,1.768424e+09,825369,0,cd1b64f4,1616103400,1.768424e+09,1,2026-01-14 20:59:56.440064+00:00
2026-01-14 23:51:21.601146+00:00,1.768435e+09,Script:216026,1.768435e+09,1091779,0,cd1b64f4,1616103400,1.768435e+09,2,2026-01-14 23:51:21.601146+00:00
2026-01-15 20:42:15.436353+00:00,1.768510e+09,Script:113462,1.768510e+09,872404,0,cd1b64f4,1616103400,1.768510e+09,1,2026-01-15 20:42:15.436353+00:00

In [134]:
# Start
df_start = getEfdData(
           client=efd_client,
           topic="lsst.sal.Scheduler.command_start",
           columns=["*"],
           begin=start_time,
           end=end_time,
)

In [135]:
df_start['timestamp'] = df_start.index
df_start

,configurationOverride,private_efdStamp,private_identity,private_kafkaStamp,private_origin,private_rcvStamp,private_revCode,private_seqNum,private_sndStamp,salIndex,timestamp
2026-01-10 01:21:58.386950+00:00,fbs_config_lsst_survey_block_419.yaml,1.768008e+09,Script:111453,1.768008e+09,3400085,0,52da5621,1851544648,1.768008e+09,1,2026-01-10 01:21:58.386950+00:00
2026-01-10 23:51:17.371641+00:00,auxtel_fbs_spec_flex_survey.yaml,1.768089e+09,Script:213822,1.768089e+09,3988392,0,52da5621,1851544648,1.768089e+09,2,2026-01-10 23:51:17.371641+00:00
2026-01-11 00:32:40.893540+00:00,fbs_config_lsst_survey_block_419.yaml,1.768092e+09,Script:112073,1.768092e+09,3946145,0,52da5621,1851544648,1.768092e+09,1,2026-01-11 00:32:40.893540+00:00
2026-01-11 01:36:33.243459+00:00,auxtel_fbs_spec_flex_survey.yaml,1.768095e+09,Script:213884,1.768095e+09,4023197,0,52da5621,1851544648,1.768095e+09,2,2026-01-11 01:36:33.243459+00:00
2026-01-11 14:09:08.158330+00:00,auxtel_fbs_spec_flex_survey.yaml,1.768141e+09,Script:214385,1.768141e+09,141507,0,52da5621,1851544648,1.768141e+09,2,2026-01-11 14:09:08.158330+00:00
2026-01-12 00:07:12.551209+00:00,auxtel_fbs_spec_flex_survey.yaml,1.768176e+09,Script:214416,1.768176e+09,150391,0,52da5621,1851544648,1.768176e+09,2,2026-01-12 00:07:12.551209+00:00
2026-01-12 07:03:26.375660+00:00,fbs_config_lsst_survey_block_419.yaml,1.768201e+09,Script:112758,1.768201e+09,376781,0,52da5621,1851544648,1.768201e+09,1,2026-01-12 07:03:26.375660+00:00
2026-01-12 23:51:23.522967+00:00,auxtel_fbs_spec_flex_survey.yaml,1.768262e+09,Script:215018,1.768262e+09,504670,0,52da5621,1851544648,1.768262e+09,2,2026-01-12 23:51:23.522967+00:00
2026-01-13 04:39:17.389900+00:00,fbs_config_lsst_survey_block_419.yaml,1.768279e+09,Script:112987,1.768279e+09,535953,0,52da5621,1851544648,1.768279e+09,1,2026-01-13 04:39:17.389900+00:00
2026-01-13 23:51:31.544646+00:00,auxtel_fbs_spec_flex_survey.yaml,1.768348e+09,Script:215427,1.768348e+09,744080,0,52da5621,1851544648,1.768348e+09,2,2026-01-13 23:51:31.544646+00:00
2026-01-14 20:59:57.500433+00:00,fbs_config_lsst_survey_block_419.yaml,1.768424e+09,Script:113374,1.768424e+09,825369,0,52da5621,1851544648,1.768424e+09,1,2026-01-14 20:59:57.500433+00:00
2026-01-14 23:51:22.679519+00:00,auxtel_fbs_spec_flex_survey.yaml,1.768435e+09,Script:216026,1.768435e+09,1091779,0,52da5621,1851544648,1.768435e+09,2,2026-01-14 23:51:22.679519+00:00
2026-01-15 20:42:16.506922+00:00,fbs_config_lsst_survey_block_419.yaml,1.768510e+09,Script:113462,1.768510e+09,872404,0,52da5621,1851544648,1.768510e+09,1,2026-01-15 20:42:16.506922+00:00